/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pp_qq_common_in_android_demo_NativeTest */

#ifndef _Included_org_pp_qq_common_in_android_demo_NativeTest
#define _Included_org_pp_qq_common_in_android_demo_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pp_qq_common_in_android_demo_NativeTest
 * Method:    CommonTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_pp_1qq_common_1in_1android_1demo_NativeTest_CommonTest
  (JNIEnv *, jclass);

/*
 * Class:     org_pp_qq_common_in_android_demo_NativeTest
 * Method:    RRIDTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_pp_1qq_common_1in_1android_1demo_NativeTest_RRIDTest
  (JNIEnv *, jclass);

/*
 * Class:     org_pp_qq_common_in_android_demo_NativeTest
 * Method:    FormatterTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_pp_1qq_common_1in_1android_1demo_NativeTest_FormatterTest
  (JNIEnv *, jclass);

/*
 * Class:     org_pp_qq_common_in_android_demo_NativeTest
 * Method:    HexCodingTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_pp_1qq_common_1in_1android_1demo_NativeTest_HexCodingTest
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
